#### configuration

VERSION        = 3.16.1
NAME           = vimperator
UUID           = vimperator@mozdev.org
MIN_VERSION    = 52.0
MAX_VERSION    = 56.2

-include private.properties

include ../common/Makefile
